name: three
version: 0.2.1
description: >
  A port of the three.js JavaScript 3D engine to Dart.
author:
- Robert Silverton <rob@unwrong.com>
- Nelson Silva <nelson.silva@inevo.pt>
- Adam Singer <financeCoding@gmail.com>
- John <jwbito@gmail.com>
homepage: http://threedart.github.com/three.dart/