name: three
version: 0.2.5+1
authors:
- Robert Silverton <rob.silverton@gmail.com>
- Nelson Silva <nelson.silva@inevo.pt>
- Adam Singer <financeCoding@gmail.com>
- John <jwbito@gmail.com>
- Anders Forsell http://aforsell.blogspot.com/
description: A port of the three.js JavaScript 3D engine to Dart.
homepage: http://threedart.github.com/three.dart/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.11.0'
  vector_math: '>=1.3.5 <1.5.0'
dev_dependencies:
  hop: '>=0.30.0 <0.31.0'
  unittest: any
